# Triggers
trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# variables
variables:
  AZURE_VARIABLE: 112263 
  GIT_REPO: $(Build.Repository.Name)
  GIT_BRANCH: $(Build.SourceBranchName)
  SERVER_NAME: $(Agent.MachineName)
  ID: $(Agent.Id)
  JOB_STATUS: $(Agent.JobStatus)
  AGENT_NAME: $(Agent.Name)
  AGENT_OS: $(Agent.OS)
  AGENT_ARCH: $(Agent.OSArchitecture)
  MY_NAME: "Somayyah Mohammed"

# Steps
steps:

# Say hello
- script: echo Hello, ICT DevOps!
  displayName: 'Say hello'

# Start the build process
- script: bash build.sh $AZURE_VARIABLE $GIT_REPO $GIT_BRANCH $SERVER_NAME $ID $JOB_STATUS $AGENT_NAME $AGENT_OS $AGENT_OSARCH $MY_NAME
  displayName: 'Run build script'

# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'somayyah@13.90.97.208'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true

# release

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'githubConnection'
    repositoryName: 'Somayyah/devops-ci-demo'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v1.*'
    title: 'first_release'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

