# Triggers

trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# variables
variables:
  AZURE_VARIABLE: 112263 
  GIT_REPO: $(Build.Repository.Name)
  GIT_BRANCH: $(Build.SourceBranchName)
  SERVER_NAME: $(Agent.MachineName)
  ID: $(Agent.Id)
  JOB_STATUS: $(Agent.JobStatus)
  AGENT_NAME: $(Agent.Name)
  AGENT_OS: $(Agent.OS)
  AGENT_ARCH: $(Agent.OSArchitecture)
  MY_NAME: "Somayyah Mohammed"
  MajorVersion: 1
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]
  BUILD_DIR: "v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)"

# Steps
steps:

# Say hello
- script: echo Hello, ICT DevOps!
  displayName: 'Say hello'

# Start the build process
- script:
    bash build.sh $AZURE_VARIABLE $GIT_REPO $GIT_BRANCH $SERVER_NAME $ID $JOB_STATUS $AGENT_NAME $AGENT_OS $AGENT_OSARCH $MY_NAME
  displayName: 'Run build script'

# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'somayyah@13.90.97.208'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true

# release

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_Somayyah'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'web/index.html'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(BUILD_DIR).zip'
    replaceExistingArchive: true

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'somayyah@13.90.97.208'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**'
    targetFolder: '/var/www/html/releases'
    readyTimeout: '20000'
    cleanTargetFolder: false
    overwrite: false
