# Triggers
trigger:
- master

# Pools
pool:
  vmImage: 'ubuntu-latest'

# variables
variables:
  AZURE_VARIABLE: 112263 
  GIT_REPO: $(Build.Repository.Name)
  GIT_BRANCH: $(Build.SourceBranchName)
  SERVER_NAME: $(Agent.MachineName)


# Steps
steps:

# Say hello
- script: echo Hello, ICT DevOps!
  displayName: 'Say hello'

# Start the build process
- script: bash build.sh $AZURE_VARIABLE $GIT_REPO $GIT_BRANCH $SERVER_NAME
  displayName: 'Run build script'

# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'somayyah@13.90.97.208'
    sourceFolder: 'web/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true

